name: image_viewer_page
description: A customizable fullscreen image viewer with pinch-to-zoom, swipe-to-dismiss, and smooth animated transitions (flip, fade, cube, etc).
version: 1.0.1
homepage: https://github.com/RathaIct/ImageViewerPage
repository: https://github.com/RathaIct/ImageViewerPage
issue_tracker: https://github.com/RathaIct/ImageViewerPage/issues
maintainer: Hin Ratha (@RathaIct)
topics:
  - image-view
  - image-gallery

screenshots:
  - description: "TransformText thumbnail "
    path: thumbnail.jpg
  - description: "Image view sample"
    path: thumbnail.gif

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
